import {
	AddressBookTabsIcon,
	ArrowLeftIcon,
	ArrowRightIcon,
	ArrowsClockwiseIcon,
	BooksIcon,
	CalendarIcon,
	CaretDownIcon,
	CaretLeftIcon,
	CaretRightIcon,
	CaretUpDownIcon,
	CaretUpIcon,
	CheckIcon,
	CircleIcon,
	CircleNotchIcon,
	DotIcon,
	DotsThreeIcon,
	DotsThreeVerticalIcon,
	EnvelopeIcon,
	EyeIcon,
	EyeSlashIcon,
	FacebookLogoIcon,
	FolderIcon,
	GearIcon,
	HouseIcon,
	InstagramLogoIcon,
	InvoiceIcon,
	ListChecksIcon,
	MagnifyingGlassIcon,
	MapPinIcon,
	MoneyWavyIcon,
	PencilIcon,
	PhoneIcon,
	PlusIcon,
	PulseIcon,
	QuestionIcon,
	ShieldCheckIcon,
	ShoppingCartIcon,
	SignOutIcon,
	TrashIcon,
	UserCircleIcon,
	UserCircleMinusIcon,
	UsersIcon,
	WarningIcon,
	X,
} from "@phosphor-icons/react/dist/ssr";
import * as React from "react";

const Icons = {
	"arrow-left": ArrowLeftIcon,
	"arrows-clockwise": ArrowsClockwiseIcon,
	"arrow-right": ArrowRightIcon,
	circle: CircleIcon,
	"user-circle-minus": UserCircleMinusIcon,
	plus: PlusIcon,
	"user-circle": UserCircleIcon,
	"shield-check": ShieldCheckIcon,
	"sign-out": SignOutIcon,
	"chevron-down": CaretDownIcon,
	"chevron-up": CaretUpIcon,
	"chevron-right": CaretRightIcon,
	"chevron-left": CaretLeftIcon,
	calender: CalendarIcon,
	"shopping-cart": ShoppingCartIcon,
	eye: EyeIcon,
	invoice: InvoiceIcon,
	eyeSlash: EyeSlashIcon,
	spinner: CircleNotchIcon,
	gear: GearIcon,
	home: HouseIcon,
	folder: FolderIcon,
	"more-vertical": DotsThreeVerticalIcon,
	"more-horizontal": DotsThreeIcon,
	dot: DotIcon,
	"money-wavy": MoneyWavyIcon,
	"question-circle": QuestionIcon,
	envelope: EnvelopeIcon,
	phone: PhoneIcon,
	search: MagnifyingGlassIcon,
	delete: TrashIcon,
	users: UsersIcon,
	books: BooksIcon,
	warning: WarningIcon,
	"list-checks": ListChecksIcon,
	"address-book-tabs": AddressBookTabsIcon,
	mail: EnvelopeIcon,
	edit: PencilIcon,
	"map-pin": MapPinIcon,
	select: CaretUpDownIcon,
	facebook: FacebookLogoIcon,
	instagram: InstagramLogoIcon,
	check: CheckIcon,
	pulse: PulseIcon,
	x: X,
};

type IconProps = React.ComponentPropsWithoutRef<(typeof Icons)["x"]> & {
	name: keyof typeof Icons;
};

const Icon = React.forwardRef<React.ElementRef<(typeof Icons)["x"]>, IconProps>(
	({ name, ...props }, ref) => {
		const Comp = Icons[name];
		return <Comp ref={ref} data-slot="icon" {...props} />;
	},
);

Icon.displayName = "Icon";

export { Icon, type IconProps, Icons };
